### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by lopezchr** [gusnips/node-koa-mvc#1]
Hi!.. when I try to install koa-mvc using this command..

```
npm install -g koa-mvc
```

I have the following error when the installation try to check a shasum:

```
npm http 200 https://registry.npmjs.org/koa-mvc/-/koa-mvc-0.0.4.tgz
npm ERR! Error: shasum check failed for /root/tmp/npm-20614-HAJykeDE/1407963005489-0.24090607813559473/tmp.tgz
```

**Comment by jguyon** [comment]
Same here.

**Comment by cesarandreu** [comment]
:+1:

**Comment by snymax** [comment]
same here any resolution

**Comment by cuteboi** [comment]
if you want to force the install, install the URL that says failed the checksum.

in this example:

npm install -g https://registry.npmjs.org/koa-mvc/-/koa-mvc-0.0.4.tgz

This will resolve the issues, from reading other places with checksum errors, it could be the node version you're using.

I installed successfully with the command I posted:

$ npm install https://registry.npmjs.org/koa-mvc/-/koa-mvc-0.0.4.tgz
koa-mvc@0.0.4 node_modules/koa-mvc
├── mkdirp@0.3.5
├── ejs@1.0.0
└── commander@1.3.2 (keypress@0.1.0)

**Comment by iho** [comment]
npm WARN package.json ssssssssssss@1.0.0 No description
npm WARN package.json ssssssssssss@1.0.0 No repository field.
npm WARN package.json ssssssssssss@1.0.0 No README data
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/home/ihor/.nvm/versions/io.js/v1.6.1/bin/iojs" "/home/ihor/.nvm/versions/io.js/v1.6.1/bin/npm" "install" "koa-mvc" "-S"
npm ERR! node v1.6.1
npm ERR! npm  v2.7.1

npm ERR! shasum check failed for /tmp/npm-6264-602a80c8/registry.npmjs.org/koa-mvc/-/koa-mvc-0.0.4.tgz
npm ERR! Expected: f4dd0ea2d151d358e499c98d2378fc44bd9fd1fd
npm ERR! Actual:   0ede276f6c646b08e53019197ba953754da3e47f
npm ERR! From:     https://registry.npmjs.org/koa-mvc/-/koa-mvc-0.0.4.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     https://github.com/npm/npm/issues

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ihor/iojs/npm-debug.log

**Comment by unlight** [comment]
Same error

**Comment by cuteboi** [comment]
@iho , you don't think it could be because you're using iojs?  it's expecting node and npm versions.  All other messages are warnings.

**Comment by iho** [comment]
@cuteboi No. 
Problem with shasum checks.

**Comment by iho** [comment]
```
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/home/ihor/.nvm/v0.11.16/bin/node" "/home/ihor/.nvm/v0.11.16/bin/npm" "install" "koa-mvc"
npm ERR! node v0.11.16
npm ERR! npm  v2.3.0

npm ERR! shasum check failed for /tmp/npm-6436-1b6622c9/registry.npmjs.org/koa-mvc/-/koa-mvc-0.0.4.tgz
npm ERR! Expected: f4dd0ea2d151d358e499c98d2378fc44bd9fd1fd
npm ERR! Actual:   0ede276f6c646b08e53019197ba953754da3e47f
npm ERR! From:     https://registry.npmjs.org/koa-mvc/-/koa-mvc-0.0.4.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/dddddd/npm-debug.log
```

```
npm install  koa-mvc
npm WARN engine koa-mvc@0.0.4: wanted: {"node":">= 0.11.9"} (current: {"node":"0.10.36","npm":"1.4.28"})
koa-mvc@0.0.4 node_modules/koa-mvc
├── mkdirp@0.3.5
├── ejs@2.3.1
└── commander@1.3.2 (keypress@0.1.0)
node -v
v0.10.36

```

**Comment by suissa** [comment]
OK here! Use  npm install -g https://registry.npmjs.org/koa-mvc/-/koa-mvc-0.0.4.tgz

 npm install -g https://registry.npmjs.org/koa-mvc/-/koa-mvc-0.0.4.tgz
npm http fetch GET https://registry.npmjs.org/koa-mvc/-/koa-mvc-0.0.4.tgz
npm http fetch 200 https://registry.npmjs.org/koa-mvc/-/koa-mvc-0.0.4.tgz
npm http request GET http://registry.npmjs.org/mkdirp
npm http request GET http://registry.npmjs.org/commander
npm http request GET http://registry.npmjs.org/ejs
npm http 200 http://registry.npmjs.org/mkdirp
npm http 200 http://registry.npmjs.org/ejs
npm http 200 http://registry.npmjs.org/commander
npm http fetch GET http://registry.npmjs.org/ejs/-/ejs-2.3.4.tgz
npm http fetch 200 http://registry.npmjs.org/ejs/-/ejs-2.3.4.tgz
npm http request GET http://registry.npmjs.org/keypress
npm http 200 http://registry.npmjs.org/keypress
/usr/local/bin/koa-mvc -> /usr/local/lib/node_modules/koa-mvc/bin/koa-mvc
npm WARN unmet dependency /usr/local/lib/node_modules/beefy/node_modules/script-injector/node_modules/trumpet/node_modules/html-tokenize/node_modules/through2 requires readable-stream@'~1.0.17' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/beefy/node_modules/script-injector/node_modules/trumpet/node_modules/readable-stream,
npm WARN unmet dependency which is version 1.0.27-1
npm WARN unmet dependency /usr/local/lib/node_modules/browserify/node_modules/module-deps/node_modules/through2 requires readable-stream@'~1.0.17' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/browserify/node_modules/readable-stream,
npm WARN unmet dependency which is version 1.0.27-1
npm WARN unmet dependency /usr/local/lib/node_modules/karma/node_modules/connect/node_modules/multiparty/node_modules/stream-counter requires readable-stream@'~1.1.8' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/karma/node_modules/connect/node_modules/multiparty/node_modules/readable-stream,
npm WARN unmet dependency which is version 1.1.13-1
koa-mvc@0.0.4 /usr/local/lib/node_modules/koa-mvc
├── mkdirp@0.3.5
├── ejs@2.3.4
└── commander@1.3.2 (keypress@0.1.0)

**Comment by gusnips** [comment]
updated version in npm and published a new package. Should be working now
Thanks!
