### ISSUE TITLE
SyntaxError: Unexpected token : while compiling ejs

### ISSUE THREAD

**Issue by pavelprudnikov** [gusnips/node-koa-mvc#4]
Hi! When i'm trying to create the app:
koa-mvc ~/www/test-koa-mvc -t green --db mysql -a local:facebook:google

create : /home/user777/www/test-koa-mvc/configs

   install dependencies:
     $ cd /home/user777/www/test-koa-mvc && npm install

   run the app:
     $ DEBUG=test-koa-mvc node --harmony app

/usr/lib/node_modules/koa-mvc/node_modules/ejs/lib/ejs.js:465
      throw e;
            ^
SyntaxError: Unexpected token : while compiling ejs
    at Function (native)
    at Object.Template.compile (/usr/lib/node_modules/koa-mvc/node_modules/ejs/lib/ejs.js:455:12)
    at Object.compile (/usr/lib/node_modules/koa-mvc/node_modules/ejs/lib/ejs.js:288:16)
    at handleCache (/usr/lib/node_modules/koa-mvc/node_modules/ejs/lib/ejs.js:147:16)
    at Object.exports.render (/usr/lib/node_modules/koa-mvc/node_modules/ejs/lib/ejs.js:315:8)
    at render_template (/usr/lib/node_modules/koa-mvc/bin/koa-mvc:216:23)
    at /usr/lib/node_modules/koa-mvc/bin/koa-mvc:120:9
    at /usr/lib/node_modules/koa-mvc/bin/koa-mvc:258:15
    at /usr/lib/node_modules/koa-mvc/node_modules/mkdirp/index.js:20:20
    at FSReqWrap.oncomplete (fs.js:99:15)

**Comment by MarcMcIntosh** [comment]
I get this too... are you running node or iojs? (wondering if it makes any diffrence)

**Comment by wingleung** [comment]
I tried on iojs and node v0.12.2 both with this error

**Comment by legendtang** [comment]
Same here. Running on node v0.12.7

**Comment by durban89** [comment]
依然有这个问题啊

**Comment by willove** [comment]
I got  same error here. node v0.12.2 & npm 2.13.1

**Comment by thanasik** [comment]
I also got the same error, with node v0.12.5

update: I actually managed to get past this error by going into the directory and running `npm install`, but then another error about an undefined object from the base code in app.js comes up

**Comment by alyrik** [comment]
Same error. Node - v0.12.7, npm - 2.14.1.

**Comment by gusnips** [comment]
Published a new version. Should be working now. Tested with node 0.12.4 and node 4.1.1
