### ISSUE TITLE
undefined is not a function  TypeError: undefined is not a function at Object.module.exports.isAuthenticated

### ISSUE THREAD

**Issue by Mararesliu** [gusnips/node-koa-mvc#7]
at Object.module.exports.isAuthenticated ../nodejs/nodejs/tms/configs/view-locals.js:14:20)

**Comment by gusnips** [comment]
I can't reproduce. What version of node are you using?

**Comment by gusnips** [comment]
Can't reproduce. Please reopen if happen again
