### ISSUE TITLE
I recommend replace default orm waterline to sequelize.

### ISSUE THREAD

**Issue by Mararesliu** [gusnips/node-koa-mvc#8]
sequelize more strong. and directly support transation. what do u think?

**Comment by gusnips** [comment]
I'll have a look and get back to you. At the time I created waterline seemed the best option
Thanks for the feedback!

**Comment by JoshZA** [comment]
sequelize doesn't support mongodb :(

**Comment by gusnips** [comment]
Sequelize only has support for SQL databases :/ better stay with waterline, which also has more support
